<Project Sdk="Microsoft.NET.Sdk">

  <!-- MIMARI KURAL: burada ASLA <PackageReference> olmayacak.
       Step 05'te Identity kullanici entity'si ve roller buraya gelecek. -->

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/BuildingBlocks.Domain/BuildingBlocks.Domain.csproj" />
  </ItemGroup>

</Project>
