sequenceDiagram
    autonumber
    actor M as 👤 Müşteri
    participant A as 🔑 Auth
    participant O as 📦 Order
    participant ODB as 🗄️ order_db
    participant R as 🐇 RabbitMQ
    participant S as 🚚 Shipment
    participant SDB as 🗄️ shipment_db

    M->>A: POST /api/auth/login
    A-->>M: JWT (rol: Customer)

    M->>O: POST /api/orders + JWT
    Note over O: customerId token'ın "sub" claim'inden —<br/>istemcinin gönderdiğine güvenilmez

    rect rgb(210, 235, 255)
    Note over O,ODB: ⚛️ TEK TRANSACTION
    O->>ODB: INSERT orders
    O->>ODB: INSERT outbox_message
    end

    O-->>M: 201 Created
    Note over M,O: Müşteri beklemedi.<br/>RabbitMQ çökük olsa bile 201 döner.

    O->>R: arka plan servisi outbox'ı süpürür
    ODB->>ODB: outbox satırı silinir
    R->>S: order-created kuyruğu

    rect rgb(255, 235, 210)
    Note over S,SDB: 🛡️ inbox kontrolü + TEK TRANSACTION
    S->>SDB: bu message_id işlendi mi?
    S->>SDB: INSERT inbox_state
    S->>SDB: INSERT shipments (TR-2026-00001)
    S->>SDB: INSERT outbox_message
    end

    S->>R: ShipmentCreated
    M->>S: GET /api/shipments/by-order/{id}
    S-->>M: trackingNumber: TR-2026-00001
