<Project Sdk="Microsoft.NET.Sdk">

  <!-- "NASIL yapilir" katmani: EF Core, Identity gibi teknoloji paketleri burada.
       Configuration.Abstractions: AddInfrastructure(IConfiguration) imzasi icin. -->

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />

    <!-- Kimlik dogrulama ve kalicilik: teknoloji paketleri SADECE bu katmanda. -->
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../AuthService.Application/AuthService.Application.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>

</Project>
